# Project: Sort
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o Sort_.o
LINKOBJ  = main.o Sort_.o
LIBS     = -L"G:/IDE/Dev-C++/Dev-Cpp/MinGW64/lib" -L"G:/IDE/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"G:/IDE/Dev-C++/Dev-Cpp/MinGW64/include" -I"G:/IDE/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/IDE/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"G:/IDE/Dev-C++/Dev-Cpp/MinGW64/include" -I"G:/IDE/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/IDE/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"G:/IDE/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Sort.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Sort_.o: Sort_.cpp
	$(CPP) -c Sort_.cpp -o Sort_.o $(CXXFLAGS)
